name: Hello world
on:
  push:
    branches:
      - master
jobs:
  Run-Hello-World:
    runs-on: ubuntu-latest
    steps:
       -
         name: Set up Go
         uses: actions/setup-go@v2
         with:
           go-version: 1.14
       -
        name: Run go
        run: go run main.go